### ISSUE TITLE
'RuntimeError: No possible words' during 'auto'

### ISSUE THREAD

**Issue by von** [von/wordle-solver#1]
> Game 179:feere
> Traceback (most recent call last):
>   File "/Users/von/develop/wordle/./wordle.py", line 584, in <module>
>     sys.exit(main())
>   File "/Users/von/develop/wordle/./wordle.py", line 580, in main
>     return args.func(w, args)
>   File "/Users/von/develop/wordle/./wordle.py", line 548, in cmd_auto
>     result, guess_num = play_game(w, word, args.debug)
>   File "/Users/von/develop/wordle/./wordle.py", line 525, in play_game
>     s.update_possible_words()
>   File "/Users/von/develop/wordle/./wordle.py", line 289, in update_possible_words
>     raise RuntimeError("No possible words.")
> RuntimeError: No possible words.

**Comment by von** [comment]
Also seen with 'weave'
